import type { NextConfig } from "next";

/* THE DOMAIN CUTOVER, and the two URLs that need catching.
 *
 * brytrco.com does not serve this site yet. As of the Ahrefs crawl of 21 Aug 2026 it was still the
 * WordPress.com install - Elementor Pro, Jetpack, Smash Balloon - with five pages on it. Vercel
 * holds brytrco.com and www.brytrco.com as aliases on the deployment, so the cutover is a DNS
 * change and not a code change.
 *
 * WHAT ALREADY WORKS AND NEEDS NOTHING. All four WordPress content URLs carry a trailing slash,
 * and Next's default trailing-slash handling already answers them: /about/, /contact/, /gallery/
 * and /recent-projects/ each 308 to their equivalent here, measured against a production build.
 * Every page on the old site has a real destination on this one, which is as clean as a migration
 * map gets. metadataBase and content/site.ts already name brytrco.com, and nothing in the repo
 * hardcodes a vercel.app URL.
 *
 * WHAT DOES NOT, AND IS WHY THIS BLOCK EXISTS. The WordPress site publishes its sitemap at
 * /sitemap_index.xml with a /page-sitemap.xml child - the Yoast and Jetpack convention - and both
 * are URLs Google has on file for this domain and re-requests. This site publishes /sitemap.xml,
 * generated by app/sitemap.ts. Without these two redirects, the day the DNS moves, both of Google's
 * known sitemap URLs start returning 404 and the sitemap signal for the domain goes dark at exactly
 * the moment the whole URL set changes. A 308 to the real sitemap costs nothing and keeps it alive.
 *
 * Permanent rather than temporary on purpose: these paths are never coming back.
 *
 * CORRECTION, 27 Aug 2026: the cutover has already happened. Ahrefs' freshest fetch of
 * https://brytrco.com/pricing returns this site, and /pricing does not exist on WordPress at all.
 * The 21 Aug crawl above was six days stale when I reasoned from it. The redirects are still right;
 * the reason they are urgent rather than preparatory is that the domain is live on this build.
 */

/* /pricing IS GONE, AND THIS IS WHY IT REDIRECTS RATHER THAN 404s.
 *
 * The page was removed on 27 Aug 2026 because every specific on it was invented. Not exaggerated -
 * invented. It stated a deposit policy ("Yes, on scheduling. The balance is due at completion"),
 * printed an example quote down to the figures (244 linear ft, 3 zones, Haven Evolution, 4
 * uplights), described financing "arranged through a third-party lender" nobody has named, claimed
 * we file HOA submissions ourselves, and promised "no design fee, no travel charge". None of it
 * came from Brytr. It was live on the client's own domain.
 *
 * A 308 to /contact rather than a 404 or a 410: the URL was in the header nav of all 78 pages and
 * in the footer, so it is in browser histories and possibly in Google's index. A visitor who wanted
 * a price should land somewhere that can give them one, which is a phone number. A 404 punishes
 * them for our mistake.
 *
 * /financing gets the same treatment and never existed as a route at all. It was the target of the
 * pricing page's own "Financing options" button, so that button was a live 404.
 *
 * DO NOT RE-ADD A PRICING PAGE FROM MEMORY. Whatever replaces this needs figures from Brytr in
 * writing, and the last version of the file is in git if the structure is ever wanted:
 * `git show c53361a:app/pricing/page.tsx`. The structure was not the problem.
 */
const nextConfig: NextConfig = {
  async redirects() {
    return [
      { source: "/pricing", destination: "/contact", permanent: true },
      { source: "/financing", destination: "/contact", permanent: true },
      { source: "/sitemap_index.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/page-sitemap.xml", destination: "/sitemap.xml", permanent: true },
    ];
  },
};

export default nextConfig;
