import type { NextConfig } from "next";

/* THE DOMAIN CUTOVER, and the two URLs that need catching.
 *
 * brytrco.com does not serve this site yet. As of the Ahrefs crawl of 21 Aug 2026 it was still the
 * WordPress.com install - Elementor Pro, Jetpack, Smash Balloon - with five pages on it. Vercel
 * holds brytrco.com and www.brytrco.com as aliases on the deployment, so the cutover is a DNS
 * change and not a code change.
 *
 * WHAT ALREADY WORKS AND NEEDS NOTHING. All four WordPress content URLs carry a trailing slash,
 * and Next's default trailing-slash handling already answers them: /about/, /contact/, /gallery/
 * and /recent-projects/ each 308 to their equivalent here, measured against a production build.
 * Every page on the old site has a real destination on this one, which is as clean as a migration
 * map gets. metadataBase and content/site.ts already name brytrco.com, and nothing in the repo
 * hardcodes a vercel.app URL.
 *
 * WHAT DOES NOT, AND IS WHY THIS BLOCK EXISTS. The WordPress site publishes its sitemap at
 * /sitemap_index.xml with a /page-sitemap.xml child - the Yoast and Jetpack convention - and both
 * are URLs Google has on file for this domain and re-requests. This site publishes /sitemap.xml,
 * generated by app/sitemap.ts. Without these two redirects, the day the DNS moves, both of Google's
 * known sitemap URLs start returning 404 and the sitemap signal for the domain goes dark at exactly
 * the moment the whole URL set changes. A 308 to the real sitemap costs nothing and keeps it alive.
 *
 * Permanent rather than temporary on purpose: these paths are never coming back.
 */
const nextConfig: NextConfig = {
  async redirects() {
    return [
      { source: "/sitemap_index.xml", destination: "/sitemap.xml", permanent: true },
      { source: "/page-sitemap.xml", destination: "/sitemap.xml", permanent: true },
    ];
  },
};

export default nextConfig;
